#################################################################
# teamName used for argocd applicaiton names and namespace names.
#################################################################
teamName: platform
#################################################################
# default Values for app-of-apps-infrastructure helm chart
#################################################################
defaults:
  # argcod application defaults
  clusterName: dev-spoke-1
  finalizers: resources-finalizer.argocd.argoproj.io
  gitopsNamespace: openshift-gitops
  # Helm defaults
  helmRepoUrl: https://rh-mobb.github.io/validated-pattern-helm-charts/
  path: charts
  chart: app-of-apps-namespaces
  targetRevision: 0.3.4
  # Vault plugin defaults.
  plugin: false
  AWS_REGION: "ap-southeast-4"
  AVP_TYPE: "awssecretsmanager"
#################################################################
# INFRASTRUCTURE Charts to be deployed.
################################################################# 
applications:
  - name: istio-demo
    apmnum: "istio"
    appserviceNumber: "demo"
    gitopsCreate: true
    gitRepoUrl: 'https://github.com/rh-mobb/rosa-cluster-config.git'
    gitPath: dev/dev-spoke-1/namespaces/istio-namespaces.yaml
    appProject:
      adGroup: PFAUTHAD
      repos:
      - 'https://github.com/foster-rh/bookinfo.git'
      destinations:
      - namespace: istio-demo
        server: 'https://kubernetes.default.svc'     
    