#################################################################
# teamName used for argocd applicaiton names and namespace names.
#################################################################
teamName: platform
#################################################################
# default Values for app-of-apps-infrastructure helm chart
#################################################################
defaults:
  # argcod application defaults
  clusterName: dev-spoke-1
  finalizers: resources-finalizer.argocd.argoproj.io
  gitopsNamespace: openshift-gitops
  # Helm defaults
  helmRepoUrl: https://rh-mobb.github.io/validated-pattern-helm-charts/
  path: charts
  chart: app-of-apps-namespaces
  targetRevision: 0.3.3
  # Vault plugin defaults.
  plugin: false
  AWS_REGION: "ap-southeast-4"
  AVP_TYPE: "awssecretsmanager"
#################################################################
# INFRASTRUCTURE Charts to be deployed.
################################################################# 
applications:
  - name: payments
    apmnum: "1234"
    appserviceNumber: "5678"
    gitopsCreate: true
    gitRepoUrl: 'https://github.com/rh-mobb/rosa-cluster-config.git'
    gitPath: dev/dev-spoke-1/namespaces/payments-1234.yaml
    appProject:
      adGroup: PFAUTHAD
      repos:
      - 'https://rh-mobb.github.io/validated-pattern-helm-charts'
      - 'https://github.com/rh-mobb/rosa-cluster-config.git'
  - name: accounting
    apmnum: "abcd"
    appserviceNumber: "efgh"
    gitopsCreate: false
    gitRepoUrl: 'https://github.com/rh-mobb/rosa-cluster-config.git'
    gitPath: dev/dev-spoke-1/namespaces/accounting-abcd.yaml
    appProject:
      adGroup: PFAUTHAD
      repos:
      - 'https://rh-mobb.github.io/validated-pattern-helm-charts'
      - 'https://github.com/rh-mobb/rosa-cluster-config.git'
    