#################################################################
# Values for app-of-apps-acm-team-onboarding chart
# Configures team namespaces and ACM infrastructure on the hub
#################################################################
gitopsNamespace: application-gitops

#################################################################
# Teams to be onboarded for ACM spoke deployment
#################################################################
applications:
  - name: istio-demo
    apmnum: "istio"
    appserviceNumber: "demo"
    gitopsCreate: true
    appProject:
      adGroup: PFAUTHAD
      repos:
        - 'https://rh-mobb.github.io/validated-pattern-helm-charts'
        - 'https://github.com/rh-mobb/rosa-cluster-config.git'
      spokeNamespaces:
        - istio-system
        - istio-demo
